BR/MR
X2LongWarOfTheChosen/LWOTC_WeaponPack pull request #17
Opened 2017-12-03 19:39 UTC by Anthogator

Still not showing up in a campaign, but most of the rest should be good

2017-12-03 20:48 UTC, TNychka requested changes

2017-12-03 20:48 UTC, TNychka commented on LWOTC_WeaponPack/Config/XComLW_WeaponPack.ini
> -[LWOTC_WeaponPack.X2StrategyElement_LaserTechs]
Why were these comments deleted?

2017-12-03 20:48 UTC, TNychka commented on LWOTC_WeaponPack/Config/XComLW_WeaponPack.ini
> +[LW_WeaponPack.X2StrategyElement_LaserTechs]
Mod name is LWOTC_WeaponPack this won't add the ini files correctly. You'll need to correct this across the entire file.

2017-12-03 20:48 UTC, TNychka commented on LWOTC_WeaponPack/Config/XComLW_WeaponPack.ini
> -[LWOTC_WeaponPack.X2StrategyElement_CoilTechs]
Please add back

2017-12-03 20:48 UTC, TNychka commented on LWOTC_WeaponPack/Config/XComLW_WeaponPack.ini
> -[LWOTC_WeaponPack.X2Item_LWMagneticSchematics]
Why was this stuff deleted?

2017-12-03 20:48 UTC, TNychka commented on LWOTC_WeaponPack/Config/XComLW_WeaponPack.ini
> -[LWOTC_WeaponPack.X2Item_LWBeamSchematics]
Please add back

2017-12-03 20:48 UTC, TNychka commented on LWOTC_WeaponPack/Config/XComLW_WeaponPack.ini
> -; MIDSHORT: SMG
Please add back

2017-12-03 20:48 UTC, TNychka commented on LWOTC_WeaponPack/Config/XComLW_WeaponPack.ini
> -; SHORTRANGE: SHOTGUN
Please add back

2017-12-03 20:48 UTC, TNychka commented on LWOTC_WeaponPack/Config/XComLW_WeaponPack.ini
> -[LWOTC_WeaponPack.X2Item_LWMagneticWeapons]
Please add back

2017-12-03 20:48 UTC, TNychka commented on LWOTC_WeaponPack/Config/XComLW_WeaponPack.ini
> -[LWOTC_WeaponPack.X2Item_LWBeamWeapons]
Please add back

2017-12-03 20:48 UTC, TNychka commented on LWOTC_WeaponPack/Config/XComLW_WeaponPack.ini
> -; TODO
Please add back

2017-12-03 20:48 UTC, TNychka commented on LWOTC_WeaponPack/Config/XComLW_WeaponPack.ini
> -[LWOTC_WeaponPack.X2Ability_SMGAbilities]
Please add back

2017-12-03 20:48 UTC, TNychka commented on LWOTC_WeaponPack/Src/LWOTC_WeaponPack/Classes/X2Item_BRSchematics.uc
> +//---------------------------------------------------------------------------------------
I know it's a pain, but can you put all of this in the con/las/mag/coil/beam schematics file?

2017-12-03 20:48 UTC, TNychka commented on LWOTC_WeaponPack/Src/LWOTC_WeaponPack/Classes/X2Item_BR_MR_Pack.uc
> +//---------------------------------------------------------------------------------------
can you put these in the con/las/mag.... weapons.uc files?

2017-12-03 20:48 UTC, TNychka commented on LWOTC_WeaponPack/Src/LWOTC_WeaponPack/Classes/X2Item_CoilWeapons.uc
> +    local array<X2DataTemplate> Weapons;
whitespace

2017-12-03 20:48 UTC, TNychka commented on LWOTC_WeaponPack/Src/LWOTC_WeaponPack/Classes/X2Item_CoilWeapons.uc
> +		Template.Requirements.RequiredTechs.AddItem(class'X2StrategyElement_LaserTechs'.default.CoilWeaponTech_Tier[0]);
All of these should be coil techs not laser techs

2017-12-03 20:48 UTC, TNychka commented on LWOTC_WeaponPack/Src/LWOTC_WeaponPack/Classes/X2Item_CoilWeapons.uc
> +		Template.BaseItem = 'AssaultRifle_MG'; // Which item this will be upgraded from
whitespace

2017-12-03 20:48 UTC, TNychka commented on LWOTC_WeaponPack/Src/LWOTC_WeaponPack/Classes/X2Item_CoilWeapons.uc
> +		Template.BaseItem = 'SMG_MG'; // Which item this will be upgraded from
whitespace

2017-12-03 20:48 UTC, TNychka commented on LWOTC_WeaponPack/Src/LWOTC_WeaponPack/Classes/X2Item_CoilWeapons.uc
> +		Template.Requirements.RequiredTechs.AddItem(class'X2StrategyElement_LaserTechs'.default.CoilWeaponTech_Tier[0]);
should be coil techs

2017-12-03 20:48 UTC, TNychka commented on LWOTC_WeaponPack/Src/LWOTC_WeaponPack/Classes/X2Item_CoilWeapons.uc
> +	Template.WeaponCat = 'pistol';
whitespace

2017-12-03 20:48 UTC, TNychka commented on LWOTC_WeaponPack/Src/LWOTC_WeaponPack/Classes/X2Item_CoilWeapons.uc
> +
whitespace

2017-12-03 20:48 UTC, TNychka commented on LWOTC_WeaponPack/Src/LWOTC_WeaponPack/Classes/X2Item_CoilWeapons.uc
> +
whitespace

2017-12-03 20:48 UTC, TNychka commented on LWOTC_WeaponPack/Src/LWOTC_WeaponPack/Classes/X2Item_CoilWeapons.uc
> +
whitespace and everything above needs to be coil

2017-12-03 20:48 UTC, TNychka commented on LWOTC_WeaponPack/Src/LWOTC_WeaponPack/Classes/X2Item_LaserWeapons.uc
> +// ***** Core properties and variables for weapons *****
this file is ok except for the whitespace here and above

2017-12-05 01:54 UTC, Anthogator commented on LWOTC_WeaponPack/Config/XComLW_WeaponPack.ini
> -; MIDSHORT WEAPONS: SMG
Will this table override the ini config values? or will the ini config values override this table?

2017-12-07 08:53 UTC, closed without merging