Config for Carbine conventional
X2LongWarOfTheChosen/LWOTC_WeaponPack pull request #46
Opened 2017-12-10 20:09 UTC by BibiFloris

2017-12-10 20:57 UTC, Danice123 commented
I sure this is not a big issue, but you should probably make the pull request after you have finished totally on the project, just in case one of the reviewers looks at it prematurely and hits the merge button or something. :)

2017-12-10 21:07 UTC, Danice123 requested changes

2017-12-10 21:07 UTC, Danice123 commented on LWOTC_WeaponPack/Src/LWOTC_WeaponPack/Classes/X2Item_LWConventionalWeapons.uc
> +	Template.strImage = "img:///UILibrary_SMG.conventional.LWConvSMG_Base";
Use
`Template.strImage = "img:///" $ default.Carbine_Conventional_ImagePath;`
here

2017-12-10 21:07 UTC, Danice123 commented on LWOTC_WeaponPack/Src/LWOTC_WeaponPack/Classes/X2Item_LWConventionalWeapons.uc
> +var config WeaponDamageValue Carbine_CONVENTIONAL_BASEDAMAGE;
It would be nice if you followed the conventions of using all caps for these variables

2017-12-10 21:07 UTC, Danice123 commented on LWOTC_WeaponPack/Src/LWOTC_WeaponPack/Classes/X2Item_LWConventionalWeapons.uc
> +var config int Carbine_CONVENTIONAL_ISUPPLIES;
Remove this line, its unnessesary

2017-12-10 21:07 UTC, Danice123 commented on LWOTC_WeaponPack/Src/LWOTC_WeaponPack/Classes/X2Ability_CarbineAbilities.uc
> +var config int Carbine_CONVENTIONAL_MOBILITY_BONUS;
It would be nice if you followed the conventions of using all caps for these variables

2017-12-10 21:07 UTC, Danice123 commented on LWOTC_WeaponPack/Src/LWOTC_WeaponPack/Classes/X2Item_LWConventionalWeapons.uc
> +var config int Carbine_CONVENTIONAL_TRADINGPOSTVALUE;
And this one

2017-12-11 01:29 UTC, TNychka requested changes
Please add Laser, Mag, Coil and beam weapons to this PR as well. It should mostly be a copy paste of what you have.

2017-12-11 14:38 UTC, TNychka submitted a review, later dismissed
Good start, but it would be great if you could do all of the carbines at once. Don't worry about how long it takes! :)

2017-12-11 14:38 UTC, TNychka commented on LWOTC_WeaponPack/Localization/SMGs/XComGame.int
> +TacticalText="<Bullet/>Carbine!!! Firing the primary weapon ends the soldier's turn, in the absence of special training.\n<Bullet/> Use upgrades recovered from ADVENT enemies to improve the SMG's tac
Can you clean this up? You get full creative freedom to write what you want here.

2017-12-11 14:38 UTC, TNychka commented on LWOTC_WeaponPack/Localization/SMGs/XComGame.int
> +AbilityDescName="SMG"
Also this shouldn't be SMG

2017-12-13 14:49 UTC, TNychka commented on LWOTC_WeaponPack/Localization/SMGs/XComGame.int
> +BriefSummary="Carbine offer a lighter and more accurat alternative to the standard smg, although they lack the same concealabilety."
Carbines offer a heavier and more accurate alternative to the standard SMG, although they lack the same concealability.

2017-12-17 16:12 UTC, Danice123 approved these changes

2017-12-17 16:14 UTC, merged